/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.ssb.gsim.client;

import com.apollographql.apollo.api.Response;
import io.reactivex.Single;
import no.ssb.gsim.client.graphql.GetUnitDatasetQuery;
import org.junit.Test;

import java.net.MalformedURLException;
import java.net.URL;

public class LibraryTest {

    @Test
    public void testGraphQL() throws MalformedURLException {

        GsimClient gsimClient = new GsimClient(null, new URL("http://35.228.232.124/lds/graphql"));

        Single<Response<GetUnitDatasetQuery.Data>> dataset = gsimClient.getUnitDataset("b9c10b86-5867-4270-b56e-ee7439fe381e");

        Response<GetUnitDatasetQuery.Data> response = dataset.blockingGet();

        GetUnitDatasetQuery.UnitDataSetById dataSetById = response.data().UnitDataSetById();
        GetUnitDatasetQuery.UnitDataStructure structure = dataSetById.unitDataStructure();
        GetUnitDatasetQuery.LogicalRecords logicalRecords = structure.logicalRecords();
        System.out.print(logicalRecords);
    }
}
